### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by ashuura** [alexkrolick/preact-photon-electron-quick-start#1]
Hi, 

First, thanks for making this boilerplate which was exactly what I was looking for!

Still, I've followed the installation steps but when I run `yarn watch` I get the following error in the output: [see log here](http://pastebin.com/fK8HGjE2)

It seems like webpack is having issues but not sure what. I've search a bit on the internets but couldn't find anything helpful. Adding `--display-error-details` to the `yarn watch` CLI in  `package.json` didn't add any useful any information...

Do you have any idea what could be missing ?

Thanks

edit: here is the generated [bundle.js](http://pastebin.com/1dge026X)

**Comment by ashuura** [comment]
Found out the issue:  it was due to the field `"target": "electron"` in the file `.babelrc` not being recognized by Babel. Simply removing the line solved the issue.

Hope it helps someone else :)

**Comment by alexkrolick** [comment]
Thanks for reporting @ashuura. The target should be in the webpack config, not the babel one. You'll need it if you want to use Electron APIs to open files, etc.
