### ISSUE TITLE
Error: Generated checksum for "electron-v1.6.0-darwin-x64.zip" did not match expected checksum.

### ISSUE THREAD

**Issue by jeberly** [alexkrolick/preact-photon-electron-quick-start#2]
Thanks for this quickstart!

While trying to get it up and running I am getting this error on `yarn install`.

```
Error: Generated checksum for "electron-v1.6.0-darwin-x64.zip" did not match expected checksum.
```

node v9.4.0

Any ideas?

Thanks in advance!

**Comment by alexkrolick** [comment]
I think that means the remote package was republished with a different checksum. I just created a new lockfile, care to try again?

**Comment by jeberly** [comment]
Thanks for quick response!  That fixed it.  Cheers!
